import { Avatar } from '@piccy/web';
import Head from 'next/head';

const data = Array.from(Array(200).keys());

export default () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main
      style={{
        gap: 12,
        flex: 1,
        padding: 12,
        display: 'flex',
        flexWrap: 'wrap',
        background: '#fff',
        flexDirection: 'row',
      }}
    >
      {data.map((_) => (
        <Avatar key={_} withColoredBorder value={_.toString()} />
      ))}
    </main>
  </>
);
